#:kivy 1.9
#:import hsv_to_rgb colorsys.hsv_to_rgb
#:import rgb_to_hsv colorsys.rgb_to_hsv

#:include lampi_touch/controls/gradient_slider.kv
#:include lampi_touch/controls/lampi_toggle.kv
#:include lampi_touch/controls/color_box.kv
#:include lampi_touch/colors.kv

BoxLayout:
  canvas.before:
    Color:
      rgba: offwhite
    Rectangle:
      pos: self.pos
      size: self.size
  orientation: 'vertical'
  BoxLayout:
    orientation: 'vertical'
    padding: 30
    size_hint_y: 0.66
    #Label for slider
    Label:
            text: app.color_value
            color: black
            font_size: "14sp"
            size_hint: 0.9, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            halign: 'center'
    #SLIDER
    GradientSlider:
      id: color_slider
      size_hint_y: 0.33
      colors: red, yellow, green, cyan, blue, magenta, red
      value: app.color_value
      on_value: app.color_value = self.value_normalized
    Button:
            text: "Submit Answer!"
            font_size: "17sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.5
            size_hint_y: 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
        