#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include lampi_touch/home.kv
#:include lampi_touch/lampi.kv
#:include lampi_touch/waitingHost.kv
#:include lampi_touch/puzzles.kv
#:include lampi_touch/addLampi.kv
#:include lampi_touch/puzz/p1_wires.kv
#:include lampi_touch/puzz/p6_wires.kv

ScreenManager:
    transition: NoTransition()
    HomeScreen:
        name: 'home'
    AddLampiScreen:
        name: 'addlampi'
    WaitingHostScreen:
        name: "waitinghost"
    LampiScreen:
        name: 'lampi'
    PuzzlesScreen:
        name: 'puzzles'
    P1WiresScreen:
        name: 'p1wires'
    P6WiresScreen:
        name: 'p6wires'
