#:kivy 1.9
#:include lampi_touch/colors.kv

<HomeScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: offwhite
            Rectangle:
                pos: self.pos
                size: self.size
        orientation: 'vertical'

        Label:
            text: "DID THIS RUN?" + (app.gameRan if app.gameRan else "No it did not...")
            color: black
            font_size: "14sp"
            size_hint: 0.9, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            halign: 'center'

        Image:
            source: 'images/lampi-bomb-title.png'
            size_hint: 0.85, 0.85
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            allow_stretch: True
            keep_ratio: True

        Button:
            text: "Start Game!"
            font_size: "17sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.5
            size_hint_y: 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]

                # blue background
                Color:
                    rgba: 0.13, 0.59, 0.95, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [18]
            on_press: app.go_to_addlampi()
