#:kivy 1.9
#:include lampi_touch/colors.kv

<PuzzlesScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: offwhite
            Rectangle:
                pos: self.pos
                size: self.size
            # outlined box

        orientation: 'vertical'
        Image:
            source: 'images/lampi-bomb-title.png'
            size_hint: 0.85, 0.85
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            allow_stretch: True
            keep_ratio: True

#        Widget:
#            size_hint: 0.85, 0.4
#            pos_hint: {'center_x': 0.5, 'center_y': 0.25}
            # outlined box
#            canvas:
#                Color:
#                    rgba: 0,0,0,1
#                Line:
#                    rounded_rectangle: self.x, self.y, self.width, self.height, 20
#                    width: 2
#                Color:
#                    rgba: 1,1,1,1

        # make multiple different buttons based on the puzzles given!
        Button:
            text: "Wires"
            font_size: "14sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.30
            size_hint_y: 0.15
            pos_hint: {'center_x': 0.18, 'center_y': 0.4}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [0]

                # blue background
                Color:
                    rgba: 0.13, 0.59, 0.95, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [0]
            on_press: app.go_to_p1wires()

        Button:
            text: "Wires 2"
            font_size: "14sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.30
            size_hint_y: 0.15
            pos_hint: {'center_x': 0.50, 'center_y': 0.4}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [0]

                # blue background
                Color:
                    rgba: 0.13, 0.59, 0.95, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [0]
            on_press: app.go_to_p6wires()

        Button:
            text: "Puzzle 2"
            font_size: "14sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.30
            size_hint_y: 0.15
            pos_hint: {'center_x': 0.82, 'center_y': 0.4}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [0]

                # blue background
                Color:
                    rgba: 0.13, 0.59, 0.95, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [0]
        

        Button:
            text: "Submit Partner Puzzle"
            font_size: "14sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.30
            size_hint_y: 0.15
            pos_hint: {'center_x': 0.5, 'center_y': 0.05}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [0]

                # green background
                Color:
                    rgba: 0.0, 0.8, 0.0, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [0]
            on_press: app.submit_partner_puzzle()
