#:kivy 1.9
#:include lampi_touch/colors.kv

<SolvedScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: offwhite
            Rectangle:
                pos: self.pos
                size: self.size
        orientation: 'vertical'

        Image:
            source: 'images/lampi-bomb-title.png'
            size_hint: 0.85, 0.85
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            allow_stretch: True
            keep_ratio: True

        Label:
                text: "Puzzle Solved!!"
                color: black
                font_size: "14sp"
                size_hint: 0.9, 0.2
                pos_hint: {'center_x': 0.5, 'center_y': 0.2}
                halign: 'center'