#:kivy 1.9
#:include lampi_touch/colors.kv

<WaitingHostScreen>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: offwhite
            Rectangle:
                pos: self.pos
                size: self.size
            # outlined box

        orientation: 'vertical'
        Image:
            source: 'images/lampi-bomb-title.png'
            size_hint: 0.85, 0.85
            pos_hint: {'center_x': 0.5, 'center_y': 0.7}
            allow_stretch: True
            keep_ratio: True

        Widget:
            size_hint: 0.85, 0.4
            pos_hint: {'center_x': 0.5, 'center_y': 0.25}
            # outlined box
            canvas:
                Color:
                    rgba: 0,0,0,1
                Line:
                    rounded_rectangle: self.x, self.y, self.width, self.height, 20
                    width: 2
                Color:
                    rgba: 1,1,1,1

        Label:
            text: "Waiting for the Expert to start the game ..."
            color: 0,0,0,1
            font_size: '14sp'
            size_hint: 0.7, 0.2
            pos_hint: {'center_x': 0.5, 'center_y': 0.35}
            text_size: self.width, None
            halign: 'center'
            valign: 'middle'

        # image appearing black cuz of the huge ass black border around it
        # LMAOO fire comment 
        Image:
            source: 'images/lampi-waiting-host.png'
            size_hint: 0.4, 0.4
            pos_hint: {'center_x': 0.5, 'center_y': 0.19}
            allow_stretch: True
            keep_ratio: True

        Button:
            text: "Puzzles"
            font_size: "12sp"
            background_color: (0,0,0,0)
            size_hint_x: 0.3
            size_hint_y: 0.1
            pos_hint: {'center_x': 0.2, 'center_y': 0.2}

            canvas.before:
                # black outline
                Color:
                    rgba: 0, 0, 0, 1
                RoundedRectangle:
                    pos: self.pos
                    size: self.size
                    radius: [20]

                # blue background
                Color:
                    rgba: 0.13, 0.59, 0.95, 1
                RoundedRectangle:
                    pos: self.x + 3, self.y + 3
                    size: self.width - 6, self.height - 6
                    radius: [18]
            on_press: app.go_to_puzzles()
