# Generated by Django 5.2.1 on 2026-04-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi_web', '0003_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='device_id',
            field=models.CharField(db_index=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
